### PR TITLE
Delete directory if function does not complete without error

### PR DESCRIPTION
**Pull request by j450h1**
See [issue23](https://github.com/ropensci/jstor/issues/23)

### CODE REVIEW

**Comment by maelle** [comment]
@j450h1 could you please resolve the conflicts?

**Comment by maelle** [comment]
@j450h1 could you please resolve the conflicts?

**Comment by maelle** [comment]
@j450h1 could you please resolve the conflicts?

**Comment by maelle** [comment]
@j450h1 could you please resolve the conflicts?

**Comment by maelle** [comment]
@j450h1 could you please resolve the conflicts?

**Comment by j450h1** [comment]
Sure, I will resolve them now.

**Comment by maelle** [comment]
Thanks a ton, I'll merge now, since the master build is failing as well independently from your PR (and I'll fix master :wink:)

**Pull request merged**
