### PR TITLE
package availability addressed

### PR DESCRIPTION
**Pull request by taddallas**
Addressed name validation issue #38 by adding `available` functionality from R package `available`.

### CODE REVIEW

**Comment by taddallas** [comment]
Thank you. The first pass was a bit inelegant, as I see now. I've added the function `is_available` which (I think) follows the naming conventions you've set up (correct me if I'm wrong), and haven't called it when it doesn't need to be called (e.g., in `createAnalysisProject`).

**Comment by stephlocke** [comment]
Thanks @taddallas for the great contribution! 

We ship stickers to folks on a monthly basis, so if you'd like us to ship you a laptop sticker, go fill out https://airtable.com/tblYkXKrZmIVIxrqD/viwhMAgnbDW5nCRGx

**Comment by stephlocke** [comment]
D'oh - I gave you the wrong link! Sorry @taddallas  https://airtable.com/shr31Z5XIyGbbwqFb

**Comment by taddallas** [comment]
:laughing: No worries. I was wondering why I needed to sign in and ask permission. Thanks for the cool sticker! And great work o the package as well.

**Pull request merged**
